### ISSUE TITLE
compatibility with french PC files and glitchs

### ISSUE THREAD

**Issue by legluondunet** [stohrendorf/CroftEngine#300]
Hello,
 I just compiled today's git croftengine on Linux.
Three things:
- 1°) I use my old french PC CD version but crosoftengine does not seem to be compatible
- 2°) when I launch croftengine , I obtain this error message:
`failed to load translations for QLocale(French, Latin, France) / "fr_FR"`
Where could I find this translations files? 
- If I use files from my Tomb Raider 1 Steam english version, croftengine launches but I have a lot of glitches on the floor:
![Capture d’écran_2023-02-24_15-08-55](https://user-images.githubusercontent.com/325405/221230934-b53e4bd2-61ea-403a-bf89-157e40b8fd2b.png)
![Capture d’écran_2023-02-24_15-07-28](https://user-images.githubusercontent.com/325405/221230937-5772eb18-cc3b-40f8-81df-b006b28063cb.png)
This glitches follow Lara when she runs.

I tried to report this issue on youtrack but it seems I haven't permission to do that. 
Thank you for your help.

**Comment by legluondunet** [comment]
"What OS are you on, what graphics card do you use, what version of CE are you using?"

I compiled CE from git yesterday.

My config:
OS: Manjaro 22.0.2 Sikaris
Kernel: x86_64 Linux 6.1.9-1-MANJARO
CPU: AMD Ryzen 9 5900HX with Radeon Graphics @ 16x 3.3GHz
GPU: AMD Radeon RX 6600M (navi23, LLVM 15.0.7, DRM 3.49, 6.1.9-1-MANJARO)
Video drivers: Mesa 22.3.5

I own Steam (english) and GOG (english) and even CD  (french) of Tomb Raider 1.

**Comment by legluondunet** [comment]
"What do you mean by "does not seem to be compatible"? Explain what you did, and what happenened."
If you agree, we will see later or in another report this point and I invite us to focus on the problem of glitches on the ground? The TR1 version I used come from steam.

**Comment by stohrendorf** [comment]
Ah, you probably found a commit that broke the graphics, but it's fixed now, although it now has a performance regression. Additionally, 2.0 has a bug that prevents importing the CD images. For importing checkout tag 1.9, then checkout tag 2.0 to play, and everything should be fine.

**Comment by stohrendorf** [comment]
I'm sorry, I messed up with the versions. You may checkout the latest `master`, it contains the fixes, but support for non-releases is limited.

**Comment by legluondunet** [comment]
I will give it a try when I will return at home.

**Comment by legluondunet** [comment]
Just tried:
- compilation OK
- launch OK
- import Steam data OK
- audio soundtrack download and playing OK
- glitches ground still present

More than words, this is a video:
https://youtu.be/nG7QYyb8IuE

**Comment by stohrendorf** [comment]
Oh, that's clearly broken shadow mapping, haven't seen that for quite a while, so I didn't recognize it immediately. As it's probably a race condition with texture access, I'm not sure I can reproduce it on my system.

**Comment by stohrendorf** [comment]
I finally got my system (partially) running again, and I can't reproduce it, neither in debug mode, nor in release mode. Please note that I was only able to test the amdgpu driver, so it might be because of different drivers. What are your drivers and versions? What is your Mesa version?

**Comment by legluondunet** [comment]
GPU: AMD Radeon RX 6600M (navi23, LLVM 15.0.7, DRM 3.49, 6.1.9-1-MANJARO)
Video drivers: Mesa 22.3.5
Do you need others info?

I launch CroftEngine directly from compile folder.
My compilation process:

git clone https://github.com/stohrendorf/CroftEngine.git
cd CroftEngine
git submodule update --init --recursive
mkdir build
cd build/
cmake -DCMAKE_BUILD_TYPE=Release ..
make
cd src
./croftengine

**Comment by stohrendorf** [comment]
Can you take a look at the log files and confirm that the "opengl ..." log lines report that it's actually using that graphics card? I have the suspicion that it's running on some integrated intel GPU, which would explain the problems.

**Comment by legluondunet** [comment]
I joined my latest log:
[croftengine.1.log](https://github.com/stohrendorf/CroftEngine/files/10908190/croftengine.1.log)

**Comment by stohrendorf** [comment]
From what I could find on the internet, the RX 6600 series seems to have a lot of issues and bugs. Many users complain their system won't even boot, others have the problem that the GPU isn't identified correctly, some have crashes, etc., although a few times it was mentioned that updating everything to the newest releases seems to have fixed stuff. I think you got bad luck with your GPU.

**Comment by legluondunet** [comment]
My GPU card is well supported now on Linux, since 6.x kernel version.
With kernel version < 6, that was not the case.
I own more that 100 3D games on Steam and all work very well  with my GPU.
Last games I played are Assasin Creed Origins and StarWars Fallen Order, two games that needs strong performance.
The issue should not be there...
Is it possible to activate a more debug mode for Croftengine?

**Comment by stohrendorf** [comment]
You can try to re-build using `-DCMAKE_BUILD_TYPE=Debug`, that enables a lot of thorough checks of the graphics calls, but performance may suffer a bit.

**Comment by legluondunet** [comment]
I just compiled a debug release with today's git.
Issue is still present.
I joined you log file.
[croftengine.0.log](https://github.com/stohrendorf/CroftEngine/files/10913876/croftengine.0.log)

**Comment by stohrendorf** [comment]
Unfortunately, that log file doesn't help. In debug mode, if there's any issue with the graphics pipeline, the engine just crashes, and this means that (in general) the pipeline is working fine for you. Additionally to that, you're the only one who reported this issue, and I'm unable to reproduce it. I looked into the code and couldn't see any issue (but that doesn't mean there is no error). As CE uses some advanced OpenGL features, it might be that it either has a rare bug (which I consider unlikely given on how many systems this runs fine on), or that you discovered a rare bug in the graphics driver. In any way, as of right now, I don't have a solution for your problem, I'm sorry.

**Comment by legluondunet** [comment]
ok, I let this report open, in case another user have the same issue as me on Linux or Windows. We'll see in several month if I can still reproduce it. 
Thanks for your help.

**Comment by stohrendorf** [comment]
FYI, the recent nvidia and AMD driver updates on my Windows system point towards the engine having some issues with resource handling regarding textures. As the shadowing is (basically) just a texture, this means that it's probably a fundamental engine issue. I'm currently investigating, but as of right now, I only have very vague suspicions what's going wrong. I hope the solution to the issues the engine has resolves your issues, but as of right now, I'm mostly clueless.

**Comment by legluondunet** [comment]
I just compiled today's git and issue is still present.

**Comment by stohrendorf** [comment]
Oh sorry, there's no fix yet, there's only hope for a fix now, just wanted to let you know about that.

**Comment by stohrendorf** [comment]
Can you try the latest master, please? There were some major changes to the render pipeline that _might_ resolve your issues.

**Comment by legluondunet** [comment]
I just compiled today's git and I have bad news, two things:
- main menu has strange colors:

![Capture d’écran_2023-03-14_20-31-37](https://user-images.githubusercontent.com/325405/225116810-456747d5-6d14-43ff-9df0-156a101c383a.png)


- Crosoftengine crashed when I launch a new game, log joined.
[croftengine.2.log](https://github.com/stohrendorf/CroftEngine/files/10972998/croftengine.2.log)

**Comment by legluondunet** [comment]
I joined another log, this time crash appeared when I select "Details levels
[croftengine.4.log](https://github.com/stohrendorf/CroftEngine/files/10973108/croftengine.4.log)
"

**Comment by stohrendorf** [comment]
Thanks, I'm pretty sure I have fixed the crashes. But I'm not sure what you mean with "strange colors", the only thing I can currently imagine is that the texture interpolation is different. Can you please try the latest master again and tell me whether it crashes _and possibly_ fixes your issues?

**Comment by legluondunet** [comment]
Crosoftengine still crash when I try to access  "Details levels" 

[croftengine.5.log](https://github.com/stohrendorf/CroftEngine/files/10973349/croftengine.5.log)

**Comment by legluondunet** [comment]
Good news: I can launch a new game without crash, but the graphical issue is till present.
[croftengine.6.log](https://github.com/stohrendorf/CroftEngine/files/10973365/croftengine.6.log)

**Comment by stohrendorf** [comment]
Oh. Thanks for that quick bug report. I'll look into it, but not today anymore, sorry. Can you tell me how you triggered that crash?

**Comment by legluondunet** [comment]
From the main menu, I selected " "Details levels"" and it crashed.

**Comment by stohrendorf** [comment]
Thanks, just fixed that crash (I hope). I only checked whether the menu worked in-game, not within the main menu.

**Comment by legluondunet** [comment]
you fixed it, no more crash.

**Comment by stohrendorf** [comment]
Sorry about bothering you again, but could you check the latest master? There were changes that will maybe make things worse for you, but I'm still trying to nail the problem down, and any change may help discover the root cause.

**Comment by legluondunet** [comment]
hello @stohrendorf , the graphic issue is still present.

**Comment by stohrendorf** [comment]
Thanks. Does make `MESA_LOADER_DRIVER_OVERRIDE=radeonsi path/to/croftengine` any difference? If so, it's an issue with the `zink` driver. If not, I'd like to prepare a special branch with a series of debugging commits to analyse what's going on here, but that would require a bit of work from you to test these commits and make screenshots. Would that be okay?

**Comment by legluondunet** [comment]
I recorded you two scenari:  normal launch and a second with the specified command:
https://youtu.be/p-8DT-xfEKU

" Would that be okay?"
Let's go!

**Comment by stohrendorf** [comment]
Okay, here's the first set of tests to try and narrow the issue down. You only need to `git fetch` and then `git checkout` the mentioned commits, and then `make`. Please use the attached quicksave to have comparable results, so I can compare it with the results on my machine.

[quicksave.zip](https://github.com/stohrendorf/CroftEngine/files/11043045/quicksave.zip)

* `6c90e569f12832eaaa6045bac26317d1d922963b` - this is a general test for texture access issues, shadows should radically change if that's an issue
* `a0bf5d2b16b569f35a80a7b45cbbd8e89905a520` - an internal check for shader issues, may radically change the output, too
* `ea1042fe7f13bdfe3af51383e1f5fdf5d6a3dce8` - some shader debugging, please take a screenshot
* `409265ed6d8c954ba593e3e6e7d7f389390da120` - some more shader debugging, please take a screenshot

Big thanks!

**Comment by legluondunet** [comment]
1° ) 6c90e569f12832eaaa6045bac26317d1d922963b
![Capture d’écran_2023-03-23_20-46-17](https://user-images.githubusercontent.com/325405/227334539-87d5bf15-2193-45f0-8a2d-0f1b100206f6.png)
[croftengine.0.log](https://github.com/stohrendorf/CroftEngine/files/11055304/croftengine.0.log)

**Comment by legluondunet** [comment]
2°) a0bf5d2b16b569f35a80a7b45cbbd8e89905a520
crash before showing main menu
[croftengine.1.log](https://github.com/stohrendorf/CroftEngine/files/11055320/croftengine.1.log)

**Comment by legluondunet** [comment]
3°) ea1042fe7f13bdfe3af51383e1f5fdf5d6a3dce8
a great change on the issue, deserve a video:
https://youtu.be/xpVu2k6gnmw

[croftengine.3.log](https://github.com/stohrendorf/CroftEngine/files/11055536/croftengine.3.log)

**Comment by legluondunet** [comment]
4°) 409265ed6d8c954ba593e3e6e7d7f389390da120
black and white
![Capture d’écran_2023-03-23_21-01-36](https://user-images.githubusercontent.com/325405/227338480-5c8ccb90-470e-4ecc-afa3-0dfa88ce8c3d.png)
![Capture d’écran_2023-03-23_21-01-51](https://user-images.githubusercontent.com/325405/227338491-3616fe74-bc4b-439d-8c90-be78d854bbef.png)
[croftengine.4.log](https://github.com/stohrendorf/CroftEngine/files/11055585/croftengine.4.log)

**Comment by stohrendorf** [comment]
Thank you very much. The crash with test 2 shouldn't have happened at all, I'll investigate. About tests 3 and 4, these basically replace some rendering outputs with with internal shader stuff that I can test against. Regarding test 3, this confirms that the shader is working correctly at the tested point, so everything is fine here, even if it changes rendering drastically for you.

**Comment by stohrendorf** [comment]
Thanks, test 4 is an actual issue that is at least a part of the problem. I need to figure out a few more tests to narrow it down further, though. This is very valuable.

**Comment by stohrendorf** [comment]
Here's the next set of tests, these skip internal stuff and should hopefully not look _that_ broken, except maybe the first one.
* `896307b614a80404d72c8df074f5a7c85163c834`
* `640489805bf227b3a9485bb0667134d84667b565`
* `d39f5012b1b762443d273702e96b6bb7e6add8be`

**Comment by legluondunet** [comment]
- test 896307b614a80404d72c8df074f5a7c85163c834
![Capture d’écran_2023-03-24_10-36-25](https://user-images.githubusercontent.com/325405/227482939-2afa5ba0-3b67-45da-86e3-6efdd50ab899.png)
![Capture d’écran_2023-03-24_10-36-42](https://user-images.githubusercontent.com/325405/227482945-2710a175-7cc3-4b9b-ab37-9a7df9458e2c.png)
[croftengine.5.log](https://github.com/stohrendorf/CroftEngine/files/11060540/croftengine.5.log)

**Comment by legluondunet** [comment]
- 640489805bf227b3a9485bb0667134d84667b565
![Capture d’écran_2023-03-24_10-36-25](https://user-images.githubusercontent.com/325405/227494643-16f9e9d9-8014-4f38-ad1d-fcb4f467647a.png)
![Capture d’écran_2023-03-24_10-36-42](https://user-images.githubusercontent.com/325405/227494650-0040eeaf-4f26-4117-853c-1e4665c56770.png)
[croftengine.6.log](https://github.com/stohrendorf/CroftEngine/files/11060907/croftengine.6.log)

**Comment by stohrendorf** [comment]
That's worrying. Does `5fdb31535359923364e99fea85eff20aed7f401d` change that?

**Comment by legluondunet** [comment]
- 5fdb31535359923364e99fea85eff20aed7f401d
![Capture d’écran_2023-03-24_18-14-57](https://user-images.githubusercontent.com/325405/227595257-c9b6995c-692f-48be-80ec-a643d57d7b07.png)
[croftengine.8.log](https://github.com/stohrendorf/CroftEngine/files/11064814/croftengine.8.log)

**Comment by stohrendorf** [comment]
Dang. How about `bfee7da6638e895b8c9aa6c603b11c5067477e4a`? If that doesn't work there are only very few places left to check.

**Comment by legluondunet** [comment]
- bfee7da6638e895b8c9aa6c603b11c5067477e4a
![Capture d’écran_2023-03-24_19-07-15](https://user-images.githubusercontent.com/325405/227605754-02700f3e-36fb-42b5-9444-3e0c19420d4e.png)
[croftengine.10.log](https://github.com/stohrendorf/CroftEngine/files/11065175/croftengine.10.log)

**Comment by stohrendorf** [comment]
Are the artifacts on her arms and legs consistent or do they change/flicker?

**Comment by legluondunet** [comment]
You have a AMD GPU card ? 
How to use your save file?

**Comment by stohrendorf** [comment]
> You have a AMD GPU card ? How to use your save file?

As the visuals are that broken right now, it doesn't matter. Anyways, within the launcher, open the "configuration" tab, and select "show data location", it will (hopefully) open your file manager at the user data folder. There's a folder `saves/tr1`, place the extracted file there.

**Comment by stohrendorf** [comment]
Huh. That video is actually interesting. How about `dee3910c6a914bbcf4dbaa296f3605742598d239`?

**Comment by legluondunet** [comment]
- dee3910c6a914bbcf4dbaa296f3605742598d239
https://youtu.be/GMmBwFJSbzs

**Comment by stohrendorf** [comment]
Uhm... I'm sorry to say, but that's probably a bug either with the driver or the graphics card. The video shows stuff that shouldn't be possible with the overall changes in that commit. There's nothing more I can do, sorry.

**Comment by stohrendorf** [comment]
Interesting. Your patch shouldn't work at all, because you're passing a texture handle name into `glBindTexture`, which expects a texture name. These are completely different things, and `glBindTexture` should report a `GL_INVALID_VALUE` error because it wasn't receiving a texture name.

The OpenGL specs say:
> GL_INVALID_VALUE is generated if texture is not a name returned from a previous call to [glGenTextures](https://docs.gl/gl4/glGenTextures).

...but the handle you're passing in was generated from a call to `glGetTextureSamplerHandle`. I couldn't find anything about this being valid in the [ARB_bindless_texture specs](https://registry.khronos.org/OpenGL/extensions/ARB/ARB_bindless_texture.txt).

**Comment by stohrendorf** [comment]
It might be that flooding the code base with a lot of `glTextureBarrier` could help, but as this is a rare case of texture corruption, I'm anything but sure.

**Comment by stohrendorf** [comment]
@legluondunet @Magnutic could you check whether the current revision reduced or, even better, resolved your issues? That would be awesome. Thanks in advance!

**Comment by legluondunet** [comment]
just tested, no changes.
